spring.application.name=demo
#spring.config.import=optional:file:.env[.properties]
spring.datasource.url=jdbc:postgresql://localhost:5434/parkdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=nikitos
spring.datasource.password=nikita3
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
server.error.include-message=always
logging.level.org.springframework.security.web.csrf=DEBUG
logging.level.org.springframework.security=DEBUG
security.jwt.secret=change-me-to-a-long-random-secret-at-least-32-chars
security.jwt.access-token-ttl=PT15M
security.jwt.refresh-token-ttl=P7D
security.jwt.issuer=demo-api
